hardware_interface:
  joints:
    - odom_x_joint
    - odom_y_joint
    - odom_z_joint
    - left_arm_0_joint
    - left_arm_1_joint
    - left_arm_2_joint
    - left_arm_3_joint
    - left_arm_4_joint
    - left_arm_5_joint
    - left_arm_6_joint
    - right_arm_0_joint
    - right_arm_1_joint
    - right_arm_2_joint
    - right_arm_3_joint
    - right_arm_4_joint
    - right_arm_5_joint
    - right_arm_6_joint
    - neck_shoulder_pan_joint
    - neck_shoulder_lift_joint
    - neck_elbow_joint
    - neck_wrist_1_joint
    - neck_wrist_2_joint
    - neck_wrist_3_joint
    - triangle_base_joint
    - left_gripper_base_gripper_left_joint
    - left_gripper_base_gripper_right_joint
    - right_gripper_base_gripper_left_joint
    - right_gripper_base_gripper_right_joint
  sim_control_mode: 1
generic_hw_control_loop:
  loop_hz: 50
  cycle_time_error_threshold: 0.03
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
velocity_controllers:
  type: iai_boxy_sim/FireHoseVelocityController
  joints:
    - odom_x_joint
    - odom_y_joint
    - odom_z_joint
    - left_arm_0_joint
    - left_arm_1_joint
    - left_arm_2_joint
    - left_arm_3_joint
    - left_arm_4_joint
    - left_arm_5_joint
    - left_arm_6_joint
    - right_arm_0_joint
    - right_arm_1_joint
    - right_arm_2_joint
    - right_arm_3_joint
    - right_arm_4_joint
    - right_arm_5_joint
    - right_arm_6_joint
    - neck_shoulder_pan_joint
    - neck_shoulder_lift_joint
    - neck_elbow_joint
    - neck_wrist_1_joint
    - neck_wrist_2_joint
    - neck_wrist_3_joint
    - triangle_base_joint
