- left_arm_0_joint
- left_arm_1_joint
- left_arm_2_joint
- left_arm_3_joint
- left_arm_4_joint
- left_arm_5_joint
- left_arm_6_joint
- right_arm_0_joint
- right_arm_1_joint
- right_arm_2_joint
- right_arm_3_joint
- right_arm_4_joint
- right_arm_5_joint
- right_arm_6_joint
- triangle_base_joint
